## Numpy Library Assignment

#### 1. What is a Python library? Why do we use Python libraries?

#### Ans : 
- Python Library : It is a collection of functions and methods.
- Use : We use python libraries in our main program so that we don't need to explicitely write the complex program for a function which is already defined in python library. We can use a function or method of simply calling it after importing the library.

#### 2. What is the difference between Numpy array and List?
#### Ans :
- Python lists are mutable data type which can be used to store the data of different type while Numpy arrays are also mutable which store the data of same type.
- Lists are slower than numpy array as Numpy array stores the data in `contiguous memory location` while lists store the data in `non-contiguous memory location`.
- Lists are created using pair of bracket `[]` while numpy arrays are created using numpy's array() function.

#### 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

#### Ans :

In [10]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Shape of the array : " , arr1.shape)
print("Size of the array : " , arr1.size)
print("Dimention of the array : " , arr1.ndim)

Shape of the array :  (3, 4)
Size of the array :  12
Dimention of the array :  2


#### 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

#### Ans 4 :

In [11]:
arr2 = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8], [9, 10, 11, 12]])

print("Accessing the first row of array : ", arr2[0])

Accessing the first row of array :  [1 2 3 4]


#### 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

#### Ans 5) 

In [13]:
arr3 = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8], [9, 10, 11, 12]])

print("Accessing the third row and fourth column of array : ", arr3[2][3])

Accessing the third row and fourth column of array :  12


#### 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

#### Ans 6)
- NOTE: extracting the elements where either row or column is odd.

In [17]:
arr4 = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8], [9, 10, 11, 12]])

for i in range(len(arr4)):
    for j in range(len(arr4[0])):
        if (i%2 != 0) or (j%2 != 0) :
            print(arr4[i][j])

2
4
5
6
7
8
10
12


#### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

#### Ans ) 
- Use the numpy random's randint function and pass the values that is to be generated in matrix.
- pass a tuple of size 3,3 to generate a 3x3 matrix of random values between 0 and 1.

In [2]:
import numpy as np

In [10]:
arr = np.random.randint(0,2 , (3,3))
arr

array([[0, 1, 0],
       [0, 1, 0],
       [1, 1, 1]])

#### 8. Describe the difference between np.random.rand and np.random.randn?
#### Ans 8) 
- The difference between np.random.rand and np.random.randn lies in the distribution from which the random numbers are drawn:

1. np.random.rand: Generates random numbers from a uniform distribution in the interval [0,1]
- Range: The numbers are between 0 (inclusive) and 1 (exclusive).

In [34]:
np.random.rand(3)

array([0.76187277, 0.96758087, 0.68043509])

2. np.random.randn:Generates random numbers from a standard normal distribution (Gaussian distribution) with mean 0 and standard deviation 1
- Range: The numbers can be positive or negative and are distributed according to the bell curve (normal distribution).

In [38]:
np.random.randn(3)

array([ 0.60017524,  0.65949945, -0.03988929])

#### 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

#### Ans 9)

In [39]:
# Original array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Increase the dimension by adding a new axis (for example, add a new axis along axis 0)
new_arr = np.expand_dims(arr, axis=0)

# Another way is using reshape to add one more dimension
new_arr_reshape = arr.reshape(1, 3, 4)

print(new_arr)
print(new_arr_reshape)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


#### 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

#### Ans )

In [15]:
arr10 = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print("Original Array : \n", arr10)
print("Transpose Array : \n",arr10.T)

Original Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose Array : 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


#### 11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
- Index wise multiplicatio'
- Matrix multiplicatio'
- Add both the matricK
- Subtract matrix B from 
- Divide Matrix B by A

In [19]:
matA = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
matB = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

print("Matrix A : \n",matA)
print("Matrix B : \n",matB)

print("Index wise Multiplication : \n" , matA * matB)
#print("Matrix Multiplication : \n" , matA @ matB)
print("Index wise Matrix Addition : \n" , matA + matB)
print("Index wise Matrix Substraction : \n" , matA - matB)
print("Index wise Matrix Division : \n" , matB / matA)

## NOTE: matrix multiplication is only possible when following condition meet:
## if matrix A is n x m and matrix B is p x q
## only if m = p then multiplication is possible.

## But in given matrix m is not equal to p hence matrix multiplication is not possible.

Matrix A : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrix B : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Index wise Multiplication : 
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Index wise Matrix Addition : 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Index wise Matrix Substraction : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Index wise Matrix Division : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 12. Which function in Numpy can be used to swap the byte order of an array?
#### Ans ) 
- The function in NumPy that can be used to swap the byte order of an array is np.ndarray.byteswap().

#### 13. What is the significance of the np.linalg.inv function?
#### Ans) 
- The np.linalg.inv function in NumPy is used to calculate the inverse of a given square matrix.

- Significance of the Inverse of a Matrix:
- For a square matrix 𝐴, the inverse 𝐴−1 is defined such that:  A⋅A−1 =I 
- where I is the identity matrix. In other words, when a matrix is multiplied by its inverse, the result is the identity matrix.

Applications: The inverse of a matrix is useful in various mathematical computations, including solving systems of linear equations, inverting transformations, and more.


#### 14. What does the np.reshape function do, and how is it used?
#### Ans )
- The np.reshape function in NumPy is used to change the shape or dimensions of an existing array without changing its data.

In [26]:
## for ex-
arr14 = np.array([1,2,3,4])

arr14.reshape(2,2)

array([[1, 2],
       [3, 4]])

#### 15. What is broadcasting in Numpy?
#### Ans )
- Broadcasting in NumPy refers to the ability to perform arithmetic operations on arrays of different shapes in an efficient way.
- For ex - 

In [25]:
arr = np.array([1, 2, 3])
scalar = 5

result = arr + scalar
print("Adding Scaler : ")
print(result)


arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2
print("Adding Array : ")
print(result)

Adding Scaler : 
[6 7 8]
Adding Array : 
[[11 22 33]
 [14 25 36]]
